- lua/efmls-configs/formatters/prettier.lua
- lua/efmls-configs/formatters/prettier_d.lua
This and other options are available as of https://github.com/mattn/efm-langserver/pull/246.
> feat(prettier, prettier_d): textDocument/rangeFormatting

- lua/efmls-configs/formatters/cbfmt.lua
- lua/efmls-configs/formatters/fish_indent.lua
- lua/efmls-configs/formatters/gofmt.lua
- lua/efmls-configs/formatters/nixfmt.lua
- lua/efmls-configs/formatters/rustfmt.lua
- lua/efmls-configs/linters/statix.lua
- supported-linters-and-formatters.md
Adds:
- cbfmt
- fish_indent
- gofmt
- nixfmt
- rustfmt
- statix
> chore: Add a bunch of formatters and linters

- lua/efmls-configs/linters/fish.lua
- supported-linters-and-formatters.md
> feat: Add `fish --no-execute` linter

- lua/efmls-configs/linters/luacheck.lua
> fix(luacheck): Ignore exit code

- lua/efmls-configs/linters/djlint.lua
- supported-linters-and-formatters.md
Greetings,
After testing this on my own setup (which doesn't use efmls-configs) for a while, I decided that support for Djlint could be useful to other people.
Hopefully this helps a bit!
> Add djlint as linter

- lua/efmls-configs/formatters/dprint.lua
> feat(formatter): add dprint configuration

- lua/efmls-configs/linters/actionlint.lua
Add configuration for [`actionlint`](https://github.com/rhysd/actionlint), which is a yaml linter for GitHub Actions.
> feat(linter): add actionlint for github actions

- doc/TODO.md
- lua/efmls-configs/linters/slim_lint.lua
Add linter configuration for [slim-lint](https://github.com/sds/slim-lint).
> Add slim-lint

- lua/efmls-configs/formatters/beautysh.lua
- lua/efmls-configs/formatters/fourmolu.lua
- lua/efmls-configs/formatters/gersemi.lua
This pull request adds the fourmolu, gersemi, and beautysh formattrs to the repository.
I believe these changes will be useful, especially since the archiving of null-ls
Thank you for your time and effort and considering this pull request.
> Added beautysh fourmolu gersemi formatters reset docs

- lua/efmls-configs/linters/selene.lua
I added the selene linter.
I think that this addition is important, since this linter has become pretty standard for lua and neovim.
Thank you for your time and effort. :)
> add selene

- doc/TODO.md
- lua/efmls-configs/formatters/biome.lua
- lua/efmls-configs/formatters/rome.lua
- lua/efmls-configs/formatters/ruff.lua
- lua/efmls-configs/formatters/shellharden.lua
- lua/efmls-configs/formatters/stylelint.lua
- lua/efmls-configs/linters/codespell.lua
- lua/efmls-configs/linters/markdownlint.lua
Thanks for this project!
Added a bunch of configs I created for my own. 
(The codespell one uses a minor hack to change the severity level, since I couldn't figure out how to change the default severity. I can remove it if it's a problem.)
> feat: add 5 formatters & 2 linters

- doc/SUPPORTED_LIST.md
- lua/efmls-configs/linters/cspell.lua
Add [CSpell](https://cspell.org/) config
> feat(linters): add cspell config

- lua/efmls-configs/formatters/latexindent.lua
Here i add support for the latexindent format script. 
Thanks :)
> add latexindent formatter

- doc/SUPPORTED_LIST.md
- lua/efmls-configs/formatters/gofumpt.lua
- Register it as a formatter
- Update documentation
> Add support for gofumpt

- lua/efmls-configs/formatters/cljstyle.lua
Hi!
Please add `cljstyle` formatter.
Thanks
> Add cljstyle formatter

- doc/SUPPORTED_LIST.md
- doc/supported-list.json
- lua/efmls-configs/formatters/typst.lua
Add support for [typstfmt](https://github.com/astrale-sharp/typstfmt), a formatter for [typst](https://typst.app/).
> feat(formatter): Add typstfmt config

- lua/efmls-configs/formatters/fnlfmt.lua
Add support for fnlfmt formatter for fennel programming language.
> Add fnlfmt config

- lua/efmls-configs/formatters/prettier.lua
- lua/efmls-configs/formatters/prettier_d.lua
https://prettier.io/docs/en/configuration.html#docsNav
> Add more prettier root markers

- lua/efmls-configs/linters/sqlfluff.lua
> feat(linter): add sqlfluff

- lua/efmls-configs/formatters/prettypst.lua
Add the [prettypst](https://github.com/antonWetzel/prettypst) formatter for Typst.
> feat(formatter): Add prettypst config

- lua/efmls-configs/formatters/swiftformat.lua
> feat(formatter): add swiftformat

- lua/efmls-configs/linters/swiftlint.lua
> feat(linter): add swiftlint

- lua/efmls-configs/formatters/biome.lua
In this PR I simply added package.json as a root marker for biome after seeing biome was unable to find the root of my project. Hope this is okey 😄 .
> feat: Add package.json as biome root marker

- doc/SUPPORTED_LIST.md
- doc/supported-list.json
- lua/efmls-configs/formatters/typstyle.lua
Add support for [typstyle](https://github.com/Enter-tainer/typstyle), a formatter for [typst](https://typst.app/).
> feat(formatters): add typstyle

- doc/SUPPORTED_LIST.md
- doc/supported-list.json
- lua/efmls-configs/formatters/mix.lua
Add mix as a formatter for Elixir.
> feat(formatters): add mix as a formatter

- doc/SUPPORTED_LIST.md
- doc/supported-list.json
- lua/efmls-configs/formatters/kdlfmt.lua
Add kdlfmt, a formatter for kdl.
https://github.com/hougesen/kdlfmt
> feat(formatters): add kdlfmt

- doc/supported-list.json
- lua/efmls-configs/formatters/gleam_format.lua
Hi there,
this adds the formatter for the gleam programming language.
I hope it helps!
> adding gleam

- doc/SUPPORTED_LIST.md
- doc/supported-list.json
- lua/efmls-configs/formatters/nixfmt.lua
Changing url for the official nix formatter.
> chore(nixfmt): update url

- lua/efmls-configs/linters/ruff.lua
> fix(linters/ruff): use github format, default to warn
