lua/efmls-configs/fs.lua

I think the check of local executable is bugged because:
- when we have a context (like node) we always return a binpath from get_local_exec and therefore we never check for global exec
- we want to print error in healthcheck ONLY if both checks fails

Fixes #1 better check of binpath

---

lua/efmls-configs/linters/eslint_d.lua

my eslint_d works perfectly, but the one from this config is not.
by double checking and comparing them I found out that this flag is important, I'm not sure what it does but works.

eslint_d needs this flag to work correctly

---

lua/efmls-configs/formatters/eslint_d.lua

Doing a search on [the changelog for eslint_d](https://github.com/mantoni/eslint_d.js/blob/master/CHANGES.md) it looks like no option called `--fix-to-stdout` ever existed, so I'm not sure how/if this ever worked. Besides that, it appears like the `--stdin-filename` argument is not actually needed and this works fine without it.
I've verified this fix by installing from my fork instead and running `:lua vim.lsp.buf.formatting_sync()` - seems to do the trick!

fix(formatters/eslint_d): fix cli arguments

---

lua/efmls-configs/linters/vint.lua

https://github.com/mattn/efm-langserver/issues/25
Alternatively, if one's using the master branch, it'd need `--stdin-display-name ${INPUT} -` but it seems like it's unmaintained and there won't be a release that supports that any time soon.

Don't use stdin for vint

---

lua/efmls-configs/formatters/shfmt.lua

If `shfmt` doesn't have the input filename, it won't find `.editorconfig`.
Reference: https://github.com/mvdan/sh/issues/577

fix(formatters/shfmt): pass in input filename

---

lua/efmls-configs/formatters/eslint.lua
lua/efmls-configs/linters/eslint.lua
lua/efmls-configs/linters/eslint_d.lua

* Without the filename, eslint cannot perform extension based overrides.
* Add missing eslint formatter.

Pass filename to eslint and eslint_d.

---

lua/efmls-configs/formatters/smlfmt.lua

`smlfmt` needlessly appends and prepends lines, hence the need for
`sed` deleting those lines.

 feat(formatter): Add smlfmt 

---

lua/efmls-configs/linters/cppcheck.lua

I fixed the cppcheck linter, because i could not get it to work. I changed the format of the output, i added rootmarkers and changed the command into a more maistream one.
I believe the changes are going to be useful for the majority of users.
Thank you for your time and effort and considering this PR.

Fix cppcheck lintFormats add rootMarkers change lintCommand

---

lua/efmls-configs/linters/flake8.lua

LspLog currently shows this error message.
```
[ERROR][2023-08-26 15:07:04] ...lsp/handlers.lua:543	"command `<redacted>/bin/flake8 -` exit with zero. probably you forgot to specify `lint-ignore-exit-code: true`."
```
Let's  add `lintIgnoreExitCode = true` for `flake8` as it has been enabled for many other linters already.

feat(linters): ignore exit code for flake8

---

lua/efmls-configs/linters/codespell.lua

@chrisgrieser referencing from this comment: https://github.com/creativenull/efmls-configs-nvim/pull/63#issuecomment-1699402368
I did not know there was a way to set a minimum severity level until I saw #67 
With this change we should see the spelling mistakes as warnings instead of errors.

fix(linters/codespell): lintSeverity starts from warn

---

lua/efmls-configs/linters/chktex.lua

I added the chktex linter. The severity is correct, the warn code is parsed, the error code is ignored. I think that this linter is a pretty basic one to include, even though it can be used with the texlab LSP. Overall i think it is worth it.
Thank you for your effort including these PRs! :)

add chktex linter

---

lua/efmls-configs/formatters/astyle.lua
lua/efmls-configs/formatters/biome.lua
lua/efmls-configs/formatters/blade_formatter.lua
lua/efmls-configs/formatters/cbfmt.lua
lua/efmls-configs/formatters/clang_format.lua
lua/efmls-configs/formatters/clang_tidy.lua
lua/efmls-configs/formatters/dprint.lua
lua/efmls-configs/formatters/eslint.lua
lua/efmls-configs/formatters/eslint_d.lua
lua/efmls-configs/formatters/fecs.lua
lua/efmls-configs/formatters/fourmolu.lua
lua/efmls-configs/formatters/joker.lua
lua/efmls-configs/formatters/lua_format.lua
lua/efmls-configs/formatters/perlimports.lua
lua/efmls-configs/formatters/php_cs_fixer.lua
lua/efmls-configs/formatters/pint.lua
lua/efmls-configs/formatters/prettier.lua
lua/efmls-configs/formatters/prettier_d.lua
lua/efmls-configs/formatters/prettier_eslint.lua
lua/efmls-configs/formatters/rome.lua
lua/efmls-configs/formatters/ruff.lua
lua/efmls-configs/formatters/shfmt.lua
lua/efmls-configs/formatters/uncrustify.lua

Currently formatting files with spaces in the filename doesn't work. With single quotes the filenames stay as as single argument instead of splitting.
I have only tested prettier, however I don't see any reason why the others wouldn't work. (As a note, the argument `smth='word    word'` is passed without quotes: `smth=word    word`)

fix(formatters): Wrap filenames in single quotes

---

doc/SUPPORTED_LIST.md
lua/efmls-configs/formatters/prettier.lua

prettier supports YAML formatting. Add appropriate metadata and
regenerate docs.

Add prettier for yaml

---

lua/efmls-configs/formatters/protolint.lua

Note: `protolint` modifies the target file directly, so the buffer does not display the changes until `:edit!` is run.

feat(formatters): protolint

---

lua/efmls-configs/formatters/sql-formatter.lua

Simple change to add support for sql-formatter. It also checks your neovim config folder for a sql-formatter config file (the options can be found on their GitHub page). 
A future change could add support to mark a json file as a rootMarker. The only thing is that there's no standard name for this file like `.editorconfig` or `.eslint` or something.

Add sql-formatter config

---

lua/efmls-configs/health/init.lua

In reference to #94 where the new health API introduces deprecated changes to the old API. Which in turn, causes some issues with this plugin.
Solution is to bump min support to nvim 0.7 and to add support for the new health API.

fix(health): bump min to 0.7, support new health api

---

lua/efmls-configs/defaults.json
lua/efmls-configs/formatters/buf.lua
lua/efmls-configs/linters/buf.lua

Note: no stdin support so buffer must be saved for formatting, linting to be accurate.

Add buf for protobuf files format/lint

---

lua/efmls-configs/formatters/ruff.lua

I suspect the command line for the ruff formatter is not suited for the newer versions of ruff.

fix(formatter/ruff): fix args

---

lua/efmls-configs/linters/ruff.lua

ruff is both a [formater](https://docs.astral.sh/ruff/formatter) and a [linter](https://docs.astral.sh/ruff/linter) for Python but only the former was added in efmls-config-nvim.
This PR is an attempt at adding the linter.
I tried to replicate what I have seen in the other linters.

feat(linter): Add ruff config

---

lua/efmls-configs/formatters/deno-fmt.lua

- add support for https://docs.deno.com/runtime/manual/tools/formatter
- it's a simpler version of https://github.com/jose-elias-alvarez/null-ls.nvim/blob/main/lua/null-ls/builtins/formatting/deno_fmt.lua
- tested with https://github.com/ryuheechul/dotfiles/commit/7cb1713785f64d36473a49908bdc2f0bc30bc2d4#diff-8772495f3e84dbcde5cdfb3f1dacd9e27b454ab6265feaecd41528e0db987250

feat(formatter): add deno fmt

---

lua/efmls-configs/formatters/biome.lua

`biome check --apply` can perform
- format
- lint fix
- organize import
although current config only supports formatting.
<https://biomejs.dev/reference/cli/#biome-check>

feat(formatter): use `biome check --apply` instead of `biome format`

---

lua/efmls-configs/linters/xo.lua

Prettier options defined in `package.json` were not picked up otherwise.

fix(linter/xo): pass filename to determine config

---

lua/efmls-configs/formatters/yapf.lua

This is similar to #109 but for yapf. Unlike 7b79dfaaa40b32b3092c7b3cc872d37fc3412c66 I suggest testing existence of `xargs` directly. Though unlikely it might be absent on linux and might be present on windows.
I also added `setup.py` to `rootMarkers`.

feat(formatter/yapf): Support range formatting. Add setup.py to rootMarkers.

---

lua/efmls-configs/linters/phpcs.lua

Pass the file path to PHPCS via `--stdin-path` to support code sniffs which rely on the file path being available.
Fixes #137

feat(linters/phpcs): pass file path to phpcs (#137)

---

lua/efmls-configs/linters/clang_tidy.lua

Without it get these kinds of errors in LspLog
```
[ERROR][2024-09-03 22:56:01] ...lsp/handlers.lua:623    'command `/usr/bin/clang-tidy "/tmp/test.c"` exit with zero. probably you forgot to specify `lint-ignore-exit-code: true`.'
```

fix(linter/clang_tidy): add lintIgnoreExitCode

---

doc/SUPPORTED_LIST.md
doc/supported-list.json
lua/efmls-configs/linters/clang_format.lua

It is already implemented as a formatter, but I find this useful to be able to show diagnostics for formatting errors. clang-tidy seems to not cover much formatting stuff in comparison.

feat(linters): add clang_format as a linter

---

lua/efmls-configs/formatters/prettier.lua
lua/efmls-configs/formatters/prettier_d.lua

Not sure why those were changed from `tabSize` to `tabWidth` in https://github.com/creativenull/efmls-configs-nvim/commit/ddc7c542aaad21da594edba233c15ae3fad01ea0, but the change was wrong.
Current main generates this command
```sh
2025/03/28 20:29:26 /nix/store/45a6c4yagzgpdckl0b88r92br4apdixv-prettier-3.5.3/bin/prettier --stdin --stdin-filepath '/Users/konrad/Code/github.com/konradmalik/neovim-flake/config/nvim/snippets/all.json'
```
understandable, because there's no such parameter as `tabWidth` defined.
while with the fix in this PR we have (notice tab-width)
```sh
2025/03/28 20:16:28 /nix/store/45a6c4yagzgpdckl0b88r92br4apdixv-prettier-3.5.3/bin/prettier --stdin --stdin-filepath '/Users/konrad/Code/github.com/konradmalik/neovim-flake/config/nvim/snippets/all.json'   --tab-width 4
``` …

fix: lsp spec defines tabSize not tabWidth

---

lua/efmls-configs/formatters/mix.lua

mix format was incorrectly getting `$FILENAME` as it's `--stdin-filename` value instead of `${INPUT}`, which is what is specified in the EFM schema. This would result in empty output which could result in erasing your elixir files. Especially noticeable when formatting on `BufWritePre`.

changes mix format --stdin-filename value
